### ISSUE TITLE
Question on paging (please see below)

### ISSUE THREAD

**Issue by PC-Doctor666** [kiznit/rainbow-os#2]
Howdy good sir! I had stumbled upon a comment of yours for paging days on OS-dev. I have a question or two for you in regards to ARM64 paging. The first question is based off the comments I seen in your code. Does each page table specify a virtual address range used by this table? The second question I have is are you mapping the page global directory into entry 510 before mapping the kernel into entry 511?

Forgive me for opening this issue! I kept putting off asking this but thought I'd finally reach out

Regards PC-Doctor

**Comment by kiznit** [comment]
It's been a while since I worked on this and I am not sure I completely understand your questions. I have been trying to map memory on arm64 the same way I do it on x86_64, which is using recursive page mapping. The recursion is on entry 510 as we want/need to use 511 for the kernel on x86_64. I decided to keep it like that on both architectures to simplify my life, but this would likely change eventually.

Memory mapping on arm64 is setup by the bootloader: TTBR0 is used for user space and TTBR1 for kernel space. You can find all the details in arm64's version of **JumpToKernel()**: https://github.com/kiznit/rainbow-os/blob/master/boot/src/aarch64/trampoline.cpp#L33C19-L92.

Please send me by email if you want to discuss something, thanks.
